"""Store Protocol — both SQLite and Postgres backends implement this."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class Store(Protocol):
    def init(self) -> None: ...
    def load_snapshot(self, conv_data: dict) -> bool: ...
    def chunk_snapshot(self, conv_data: dict, *, skip_embeddings: bool = False) -> int: ...
    def list_snapshots(self, *, source: str | None = None,
                       author: str | None = None, limit: int = 1000) -> list[dict]: ...
    def get_snapshot(self, convaix_id: str) -> dict | None: ...
    def get_snapshot_history(self, conv_id: str) -> list[dict]: ...
    def get_chunks(self, convaix_id: str) -> list[dict]: ...
    def search_chunks(self, query: str, *, source: str | None = None,
                      limit: int = 10, mode: str = "hybrid") -> list[dict]: ...
    def search_conversations(self, query: str, *, source: str | None = None,
                              limit: int = 20) -> list[dict]: ...
    def create_discussion(self, title: str, author: str) -> str: ...
    def add_discussion_message(self, discussion_id: str, author: str, content: str) -> int: ...
    def list_discussions(self, limit: int = 50) -> list[dict]: ...
    def get_discussion_messages(self, discussion_id: str) -> list[dict]: ...
    def close(self) -> None: ...
